# Generated by Django 5.1.7 on 2025-03-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='borrower_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Student/Staff ID'),
        ),
    ]
