# Generated by Django 5.1.7 on 2025-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-checkout_date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_notes',
            field=models.TextField(blank=True, verbose_name='Return Condition Notes'),
        ),
    ]
