# Generated by Django 5.1.7 on 2025-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_transaction_options_transaction_return_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returner_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='returner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
