# Generated by Django 5.1.7 on 2025-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_transaction_returner_id_transaction_returner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='condition_after',
            new_name='condition_notes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='condition_notes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='condition_before',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='return_notes',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('CHECKED_OUT', 'Checked Out')], default='AVAILABLE', max_length=20),
        ),
    ]
