# Generated by Django 5.1.7 on 2025-04-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_adviser_author_panelist_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='abstract',
            field=models.TextField(blank=True, help_text='Enter the abstract of the book.', null=True),
        ),
    ]
