# Generated by Django 5.1.7 on 2025-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_keyword_alter_transaction_returned_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for this book.'),
        ),
    ]
