# Generated by Django 5.1.7 on 2025-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_keywords_delete_keyword_book_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='approval_sheet',
            field=models.FileField(blank=True, help_text='Upload the approval sheet (PDF only)', null=True, upload_to='approval_sheets/'),
        ),
    ]
